### ISSUE TITLE
set selectedSegmentIndex

### ISSUE THREAD

**Issue by Frankity** [jamesrochabrun/CustomSegmentedControl#1]
hi, i have a question, how can i set the selectedSegmentIndex from code
i mean by default the selected item is the first, what if want to set the second always on load.
this is my case:
when i make a query using search bar the Segment show the first item as selected but the view is the second -->
![img_0049](https://user-images.githubusercontent.com/1179431/50171157-b0d0e500-02bf-11e9-852b-fc2f4c65873d.PNG)

this should be the order the first item should show the first view -->
![img_778ead49f10a-1](https://user-images.githubusercontent.com/1179431/50171191-c7773c00-02bf-11e9-9274-e3eaee36cedf.jpeg)

this is the result i want but only happens if i click on second item -->
![img_0050](https://user-images.githubusercontent.com/1179431/50171236-e8d82800-02bf-11e9-9203-40223e8d6f9c.PNG)

**Comment by jamesrochabrun** [comment]
CustomCustomSegmentedControl  has a public property selectedSegmentedindex that can be set to 1 for your case so when you instantiate the CustomSegmentedControl class you can ...

`@IBOutlet weak var colorsSegmentedControl: CustomSegmentedControl! {
        didSet {            
            colorsSegmentedControl.selectedSegmentIndex = 1
        }
    }`

I think that should do what you expect.

**Comment by Frankity** [comment]
i added a public function inside the CustomSegmentedControl Class like

`public func moveBottomLineTo(pos: Int) {
        moveThumbView(at: pos)
    }`

which let me do this on my viewcontroller:

`            segmentView!.moveBottomLineTo(pos: 1);
`

i tried your solution but wont work, that's weird.

thanks for response
